ajout de whiteroom

diff --git a/zsh/zshrc_functions b/zsh/zshrc_functions
--- a/zsh/zshrc_functions
+++ b/zsh/zshrc_functions
@@ -298,6 +298,85 @@ function getwifi ()
     fi
 }
 
+function open_path ()
+{
+    while getopts ":p:" opt; do
+        case $opt in
+            p) path="${OPTARG}"
+            ;;
+            \?) echo "Invalid option -${OPTARG}" >&2
+            exit 1
+            ;;
+        esac
+    done
+
+    case $path in
+        build)
+            path="./build"
+        ;;
+        coverage)
+            path="./coverage"
+        ;;
+    esac
+
+    isWSL=$(uname -a | grep WSL)
+    if [[ -n "${isWSL}" ]]; then
+        path=$(wslpath -w ${path})
+    fi
+
+    nautilus "${path}"
+}
+
+function open_browser ()
+{
+    while getopts ":f:u:p:" opt; do
+        case $opt in
+            f) file="${OPTARG}"
+            ;;
+            u) url="${OPTARG}"
+            ;;
+            p) port="${OPTARG}"
+            ;;
+            \?) echo "Invalid option -${OPTARG}" >&2
+            exit 1
+            ;;
+        esac
+    done
+
+    address=""
+    if [ -n "${file}" ]; then
+        case $file in
+            coverage)
+                launcher=${BROWSER}
+                file="./coverage/lcov-report/index.html"
+            ;;
+        esac
+
+        isWSL=$(uname -a | grep WSL)
+        if [[ -n "${isWSL}" ]]; then
+            file=$(wslpath -w ${file})
+        fi
+        address="${file}"
+    fi
+
+    if [ -n "${port}" ]; then
+        pattern="^([0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$"
+        if [[ ${port} =~ ${pattern} ]]; then
+            url="${url}:${port}"
+        fi
+    fi
+
+    if [ -n "${url}" ]; then
+        pattern="^(http|https)://"
+        if (! [[ "${url}" =~ ${pattern} ]]); then
+            url="https://${url}"
+        fi
+        address="${url}"
+    fi
+
+    firefox "${address}"
+}
+
 rpg () {
     rpg-cli "$@"
     cd "$(rpg-cli pwd)"
